SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio / 1.07 FROM producto;
SELECT nombre AS 'Nombre del producto', precio AS 'Precio en Euros', precio / 1.07 AS 'Precio en dólares' FROM producto;
SELECT UPPER (nombre), precio FROM producto;
SELECT LOWER (nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1, 2)) FROM fabricante; 
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, FLOOR(precio) FROM producto;
SELECT fabricante.codigo FROM fabricante INNER JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT DISTINCT fabricante.codigo FROM fabricante INNER JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT * FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 0, 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre, codigo_fabricante FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante WHERE fabricante.codigo = producto.codigo;
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante WHERE fabricante.codigo = producto.codigo ORDER BY fabricante.nombre ASC;
SELECT p.codigo AS 'Código Producto', p.nombre, p.codigo_fabricante, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, MIN(p.precio), f.nombre AS'Nombre fabricante' FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, MAX(p.precio), f.nombre AS'Nombre fabricante' FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT nombre FROM producto WHERE codigo_fabricante = '2';
SELECT nombre, precio FROM producto WHERE producto.precio > '200';
SELECT nombre FROM producto WHERE codigo_fabricante = 1 OR codigo_fabricante = 3 OR codigo_fabricante = 5;
SELECT nombre FROM producto WHERE codigo_fabricante IN(1,3,5);